# Generated by Django 4.2.2 on 2023-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute', models.CharField(max_length=400)),
                ('Academic_Program_Name', models.CharField(max_length=300)),
                ('Seat_Type', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
                ('Opening_Rank', models.IntegerField()),
                ('Closing_Rank', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Round', models.IntegerField()),
            ],
        ),
    ]
